#!/bin/bash

sshd_config_bak=$(cat /etc/ssh/sshd_config |grep -v "Banner")
echo "$sshd_config_bak" > /etc/ssh/sshd_config
echo "Banner /etc/bannerssh" >> /etc/ssh/sshd_config
service ssh restart 1>/dev/null 2>/dev/null
service sshd restart 1>/dev/null 2>/dev/null
if [ -f /etc/bannerssh ]
then
banner=$(cat /etc/bannerssh)
else
banner="Não há um banner no momento"
fi
echo -e "\033[1;32mBanner atual\n\n\033[1;37m$banner\n\033[0m"
echo "Qual banner deseja adicionar (ctrl + c para sair )"
echo "De um nome ao Servidor"
read -p ": " nome
echo "Bem Vindo(a) ao Servidor $nome" > $local
echo "Digite a mensagem para seu Banner"
read -p ": " bannerssh
echo "$bannerssh" > /etc/bannerssh
echo "|P*R*O*I*B*I*D*O|" >> $local
echo "|*xTorrents*xSPAM*xDDoS*xHACKING*xFLOOD| " >> $local
echo "Informe seu Telegram para contato"
read -p ":@" telegram
echo "Entre em contato pelo Telegram @$telegram" >> $local
echo "|Config by: @ColtSeals|" >> $local
echo "|NERDOLOGIA VPS|" >> $local
service ssh restart 1> /dev/null 2>/dev/null
service sshd restart 1>/dev/null 2>/dev/null
